exec-once = qs -c arisu
exec-once = awww-daemon

windowrule {
    name = .*
    match:class = .*
    border_size = 2
}

general {
    gaps_in  = 10
    gaps_out = 12
}

decoration {
    rounding = 24
}

# Fix some ozone related issues
xwayland {
    enabled = true
}

input {
    numlock_by_default = true
}