exec-once = qs -c arisu
exec-once = awww-daemon

windowrule {
    name = .*
    match:class = .*
    border_size = 2
}

# Fix some ozone related issues
xwayland {
    enabled = true
}

input {
    numlock_by_default = true
}