
unbind = SUPER, Q
unbind = SUPER, RETURN

bind = SUPER, Q, killactive
bind = SUPER, RETURN, exec, kitty 
bindr = SUPER, SUPER_L, exec, pkill fuzzel || fuzzel

bind = SUPER, TAB, exec, qs ipc -c arisu call overview toggle