[main]
font=JetBrainsMono:size=13
dpi-aware=yes
prompt="~ "
#line-height=22
#anchor=top
#y-margin=100
#width=45
#lines=5
layer=overlay
exit-on-keyboard-focus-loss=yes


[colors]
background=1e1e2edd
text=cdd6f4ff
match=f38ba8ff
selection=313244ff
selection-text=cdd6f4ff
selection-match=f38ba8ff
border=89b4faff

[border]
width=2
radius=10

[dmenu]
exit-immediately-if-empty=yes