# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User

# Tips:
# - move (resize) windows:       SUPER+SHIFT+R, arrow keys
# - move (workspace) windows:    SUPER+SHIFT+R, [0-9]
# - switch workspaces:           SUPER+[0-9]
# - swicth relative workspace +1:SUPER, arrow keys
# - swicth relative workspace +5:SUPER+CTRL, arrow keys
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Switch workspaces with SUPER + [0-9]
bind = SUPER, ampersand, workspace, 1
bind = SUPER, eacute, workspace, 2
bind = SUPER, quotedbl, workspace, 3
bind = SUPER, apostrophe, workspace, 4
bind = SUPER, parenleft, workspace, 5
bind = SUPER, minus, workspace, 6
bind = SUPER, egrave, workspace, 7
bind = SUPER, underscore, workspace, 8
bind = SUPER, ccedilla, workspace, 9
bind = SUPER, agrave, workspace, 10 

bind = SUPER, right, workspace, +1
bind = SUPER, left, workspace, -1
bind = SUPER+CTRL, left, workspace, -9
bind = SUPER+CTRL, right, workspace, +9


bind = SUPER+SHIFT, ampersand, movetoworkspacesilent, 1
bind = SUPER+SHIFT, eacute, movetoworkspacesilent, 2
bind = SUPER+SHIFT, quotedbl, movetoworkspacesilent, 3
bind = SUPER+SHIFT, apostrophe, movetoworkspacesilent, 4
bind = SUPER+SHIFT, parenleft, movetoworkspacesilent, 5
bind = SUPER+SHIFT, minus, movetoworkspacesilent, 6
bind = SUPER+SHIFT, egrave, movetoworkspacesilent, 7
bind = SUPER+SHIFT, underscore, movetoworkspacesilent, 8
bind = SUPER+SHIFT, ccedilla, movetoworkspacesilent, 9
bind = SUPER+SHIFT, agrave, movetoworkspacesilent, 10 

#bind = Super, F, fullscreen
#bind = ALT, TAB, cyclenext 

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above