# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User

# Tips:
# - move (resize) windows:       SUPER+SHIFT+R, arrow keys
# - move (workspace) windows:    SUPER+SHIFT+R, [0-9]
# - switch workspaces:           SUPER+[0-9]
# - swicth relative workspace +1:SUPER, arrow keys
# - swicth relative workspace +5:SUPER+CTRL, arrow keys


#bind = Super, F, fullscreen
#bind = ALT, TAB, cyclenext 

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above