# DEPENDENCIES
# Quickshell 0.2.1 (aur)
# Awww 0.11.2-master2 (aur)

# See https://wiki.hypr.land/Configuring/Keywords/
## Keys ##
$mainMod = SUPER # Sets "Windows" key as main modifier

## Programs ##
$terminal = kitty
$fileManager = dolphin
$menu = fuzzel

## Configs ##
$qsConfig = arisu


source = ~/.config/hypr/arisu/env.conf
source = ~/.config/hypr/arisu/custom/env.conf

source = ~/.config/hypr/arisu/execs.conf
source = ~/.config/hypr/arisu/general.conf
source = ~/.config/hypr/arisu/keybinds.conf

source = ~/.config/hypr/arisu/custom/execs.conf
source = ~/.config/hypr/arisu/custom/general.conf
source = ~/.config/hypr/arisu/custom/keybinds.conf
