# DEPENDENCIES
# Quickshell 0.2.1 (aur)
# Awww 0.11.2-master2 (aur)

source = ~/.config/hypr/arisu/default_base.conf
source = ~/.config/hypr/arisu/general.conf
source = ~/.config/hypr/arisu/keybinds.conf

source = ~/.config/hypr/arisu/custom/general.conf
source = ~/.config/hypr/arisu/custom/keybinds.conf
