#!/bin/bash

exit 1 #for now

# -----------------------
# Colors
# -----------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

sudo -v

info "Updating package lists..."
sudo pacman -Syu --noconfirm

info "Installing packages..."
sudo pacman -S hyprland kitty fuzzel dolphin chafa --noconfirm
yay --aur quickshell-git awww

success "Packages installed."

success "Installing..."
timestamp=$(date +%Y%m%d%H%M%S)
if [[ -d "$HOME/.config" ]]; then
    mv "$HOME/.config" "$HOME/.config.bak.$timestamp"
fi

REPO_DIR="$(pwd)/.config"

cp -R $REPO_DIR $HOME/